blog/urls.py
from django.urls import path
from .views import authorBlogs,BlogsUpdate,BlogsCreate

namespace='blog'
urlpatterns=[

path('author/<int:id>',authorBlogs,name='author'),
path('update/<int:id>',BlogsUpdate,name="update"),
path('create/',BlogsCreate,name="create")

    ]

blogger1/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path,include
from blog import urls
from accounts.views import loginPage

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('accounts/', include('accounts.urls')),
    path('profile/',include('profile_crud.urls')),
    path('',loginPage,name='login'),


]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profile_crud/urls.py
from django.urls import path
from .views import profileView,dashboardView

app_name='profile_crud'

urlpatterns=[
path('',profileView, name='profile'),
path('dashboard/',dashboardView, name='dashboard')
]

profile_crud/models.py
from django.db import models
from accounts.models import CustomUser



# Create your models here.
class profile(models.Model):
    user=models.OneToOneField(CustomUser,null=True,on_delete=models.CASCADE)
    full_name = models.CharField(max_length=100)
    phone_number=models.IntegerField()
    profile_image=models.ImageField(null=True,blank=True)
    is_staff = models.BooleanField(default=True)

    def __str__(self):
        return self.full_name

profile_crud/forms.py
from django.forms import ModelForm
from .models import profile


class ProfileForm(ModelForm):
    class Meta:
        model = profile
        fields = '__all__'
        # exclude = ['user']

profile_crud/views.py
from django.shortcuts import render, redirect
from .forms import ProfileForm
from .models import profile
from django.contrib.auth import get_user_model
from blog.models import Blog, Author
from django.contrib.auth.decorators import login_required

@login_required(login_url='login')
def profileView(request):
    if request.method=='POST':
        form = ProfileForm(request.POST, request.FILES, instance =request.user.profile )
        if form.is_valid():
            form.save()
            return redirect('profile_crud:dashboard')

    elif request.method=='GET':

        form=ProfileForm(instance=request.user.profile)

        context={
            'form':form
        }
        return render(request, 'html/profile.html',context)

@login_required(login_url='login')
def dashboardView(request):
    obj = Blog.objects.all()
    auth = Author.objects.all()
    name=request.user.profile.full_name


    return render(request,'html/dashboard.html',{'obj':obj,'auth':auth,'name':name})

profile_crud/templates/html/dashboard.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'plugins/images/favicon.png' %}">
    <title>My Blog DashBoard</title>
    <!-- Bootstrap Core CSS -->
    <link href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Menu CSS -->
    <link href="{% static 'plugins/bower_components/sidebar-nav/dist/sidebar-nav.min.css' %}" rel="stylesheet">
    <!-- toast CSS -->
    <link href="{% static 'plugins/bower_components/tdasoast-master/css/jquery.toast.css' %}" rel="stylesheet">
    <!-- morris CSS -->
    <link href="{% static 'plugins/bower_components/morrisjs/morris.css' %}" rel="stylesheet">
    <!-- chartist CSS -->
    <link href="{% static 'plugins/bower_components/chartist-js/dist/chartist.min.css' %}" rel="stylesheet">
    <link href="{% static 'plugins/bower_components/chartist-plugin-tooltip-master/dist/chartist-plugin-tooltip.css' %}" rel="stylesheet">
    <!-- animation CSS -->
    <link href="{% static 'css/animate.css' %}" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <!-- color CSS -->
    <link href="{% static 'css/colors/default.css' %}" id="theme" rel="stylesheet">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
<![endif]-->
</head>

<body class="fix-header">
    <!-- ============================================================== -->
    <!-- Preloader -->
    <!-- ============================================================== -->
    <div class="preloader">
        <svg class="circular" viewBox="25 25 50 50">
            <circle class="path" cx="50" cy="50" r="20" fill="none" stroke-width="2" stroke-miterlimit="10" />
        </svg>
    </div>
    <!-- ============================================================== -->
    <!-- Wrapper -->
    <!-- ============================================================== -->
    <div id="wrapper">
        <!-- ============================================================== -->
        <!-- Topbar header - style you can find in pages.scss -->
        <!-- ============================================================== -->
        <nav class="navbar navbar-default navbar-static-top m-b-0">
            <div class="navbar-header">
                <div class="top-left-part">
                    <!-- Logo -->
                    <a class="logo" href="javascript:void(0)">
                        <!-- Logo icon image, you can use font-icon also -->
                        <b>
                            <!--This is dark logo icon-->
                            <img src="{% static 'plugins/images/admin-logo.png '%}" alt="home" class="dark-logo" />
                            <!--This is light logo icon-->
                            <img src="{% static 'plugins/images/admin-logo-dark.png' %}" alt="home" class="light-logo" />
                        </b>
                        <!-- Logo text image you can use text also -->
                        <span class="hidden-xs">
                            <!--This is dark logo text-->
                            <img src="{% static 'plugins/images/admin-text.png' %}" alt="home" class="dark-logo" />
                            <!--This is light logo text-->
                            <img src="{% static 'plugins/images/admin-text-dark.png' %}" alt="home" class="light-logo" />
                        </span> 
                    </a>
                </div>
                <!-- /Logo -->
                <ul class="nav navbar-top-links navbar-right pull-right">
                    <li>
                        <a class="nav-toggler open-close waves-effect waves-light hidden-md hidden-lg" href="javascript:void(0)"><i class="fa fa-bars"></i></a>
                    </li>
                    <li>
                        <a class="profile-pic" href="#"> <img src="../../{{request.user.profile.profile_image.url}}" alt="user-img" width="36" class="img-circle"><b class="hidden-xs">{{request.user.profile.full_name}}</b></a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-header -->
            <!-- /.navbar-top-links -->
            <!-- /.navbar-static-side -->
        </nav>
        <!-- End Top Navigation -->
        <!-- ============================================================== -->
        <!-- Left Sidebar - style you can find in sidebar.scss  -->
        <!-- ============================================================== -->
        <div class="navbar-default sidebar" role="navigation">
            <div class="sidebar-nav slimscrollsidebar">
                <div class="sidebar-head">
                    <h3><span class="fa-fw open-close"><i class="ti-close ti-menu"></i></span> <span class="hide-menu">Navigation</span></h3>
                </div>
                <ul class="nav" id="side-menu">
                    <li style="padding: 70px 0 0;">
                        <a href="javascript:void(0)" class="waves-effect"><i class="fa fa-clock-o fa-fw" aria-hidden="true"></i>Dashboard</a>
                    </li>
                    <li>
                        <a href="{% url 'profile_crud:profile'%}" class="waves-effect"><i class="fa fa-user fa-fw" aria-hidden="true"></i>Profile</a>
                    </li>


                </ul>
          
            </div>
            
        </div>
        <!-- ============================================================== -->
        <!-- End Left Sidebar -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Page Content -->
        <!-- ============================================================== -->
        <div id="page-wrapper">
            <div class="container-fluid">
                <div class="row bg-title">
                    <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
                        <h4 class="page-title">Dashboard/Click <a href="{% url 'create'%}"><u>To Add New Blog</u></a></h4> </div>

                    <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
                        <ol class="breadcrumb">
                            <li><a href="{% url 'logout'%}">Logout</a></li>
                        </ol>
                    </div>
                    <!-- /.col-lg-12 -->
                </div>
                <div class="row">
                    <!-- .col -->
                    <div class="col-md-12 col-lg-8 col-sm-12">
                        <div class="white-box">
                            <h3 class="box-title">Recent Blogs</h3>
                            <div class="comment-center p-t-10">
                                {% for ob in obj %}
                                <div class="comment-body">

                                    <div class="mail-contnet">

                                        <h5><a href="{% url 'author' ob.id %}">{{ob.full_name}}</a></h5><span class="time">{{ob.created_at}}</span>
                                        <br/><span class="mail-desc">{{ob.blog_content}}</span>
                                        <a href="{% url 'update' ob.id%}">Update {{ob.blog_name}}</a>

                                    </div>
                                </div>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-6 col-sm-12">
                        <div class="panel">
                            <div class="sk-chat-widgets">
                                <div class="panel panel-default">
                                    <div class="panel-heading">
                                        AUTHOR LISTING
                                    </div>

                                    <div class="panel-body">

                                        {% for ob in auth %}

                                            <ul class="chatonline">
                                            <li>
                                                <a href="javascript:void(0)"><span>{{ob.full_name}}</span></a>
                                            </li>
                                            </ul>


                                        {% endfor %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- /.col -->
                </div>
            </div>
            <!-- /.container-fluid -->
            <footer class="footer text-center"> 2017 &copy; Ample Admin brought to you by wrappixel.com </footer>
        </div>
        <!-- ============================================================== -->
        <!-- End Page Content -->
        <!-- ============================================================== -->
    </div>
    <!-- ============================================================== -->
    <!-- End Wrapper -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- All Jquery -->
    <!-- ============================================================== -->
    <script src="{% static 'plugins/bower_components/jquery/dist/jquery.min.js' %}"></script>
    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'bootstrap/dist/js/bootstrap.min.js' %}"></script>
    <!-- Menu Plugin JavaScript -->
    <script src="{% static 'plugins/bower_components/sidebar-nav/dist/sidebar-nav.min.js' %}"></script>
    <!--slimscroll JavaScript -->
    <script src="{% static 'js/jquery.slimscroll.js' %}"></script>
    <!--Wave Effects -->
    <script src="{% static 'js/waves.js' %}"></script>
    <!--Counter js -->
    <script src="{% static 'plugins/bower_components/waypoints/lib/jquery.waypoints.js' %}"></script>
    <script src="{% static 'plugins/bower_components/counterup/jquery.counterup.min.js' %}"></script>
    <!-- chartist chart -->
    <script src="{% static 'plugins/bower_components/chartist-js/dist/chartist.min.js' %}"></script>
    <script src="{% static 'plugins/bower_components/chartist-plugin-tooltip-master/dist/chartist-plugin-tooltip.min.js' %}"></script>
    <!-- Sparkline chart JavaScript -->
    <script src="{% static 'plugins/bower_components/jquery-sparkline/jquery.sparkline.min.js' %}"></script>
    <!-- Custom Theme JavaScript -->
    <script src="{% static 'js/custom.min.js' %}"></script>
    <script src="{% static 'js/dashboard1.js' %}"></script>
    <script src="{% static 'plugins/bower_components/toast-master/js/jquery.toast.js' %}"></script>
</body>

</html>

profile_crud/templates/html/profile.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'plugins/images/favicon.png' %}">
    <title>My Blog DashBoard</title>
    <!-- Bootstrap Core CSS -->
    <link href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Menu CSS -->
    <link href="{% static 'plugins/bower_components/sidebar-nav/dist/sidebar-nav.min.css' %}" rel="stylesheet">
    <!-- animation CSS -->
    <link href="{% static 'css/animate.css' %}" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <!-- color CSS -->
    <link href="{% static 'css/colors/default.css' %}" id="theme" rel="stylesheet">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
<![endif]-->
</head>

<body class="fix-header">
    <!-- ============================================================== -->
    <!-- Preloader -->
    <!-- ============================================================== -->
    <div class="preloader">
        <svg class="circular" viewBox="25 25 50 50">
            <circle class="path" cx="50" cy="50" r="20" fill="none" stroke-width="2" stroke-miterlimit="10" />
        </svg>
    </div>
    <!-- ============================================================== -->
    <!-- Wrapper -->
    <!-- ============================================================== -->
    <div id="wrapper">
        <!-- ============================================================== -->
        <!-- Topbar header - style you can find in pages.scss -->
        <!-- ============================================================== -->
        <nav class="navbar navbar-default navbar-static-top m-b-0">
            <div class="navbar-header">
                <div class="top-left-part">
                    <!-- Logo -->
                    <a class="logo" href="{% url 'profile_crud:dashboard'%}">
                        <!-- Logo icon image, you can use font-icon also --><b>
                            <!--This is dark logo icon--><img src="{% static 'plugins/images/admin-logo.png' %}" alt="home"
                                class="dark-logo" />
                            <!--This is light logo icon--><img src="{% static 'plugins/images/admin-logo-dark.png' %}" alt="home"
                                class="light-logo" />
                        </b>
                        <!-- Logo text image you can use text also --><span class="hidden-xs">
                            <!--This is dark logo text--><img src="{% static 'plugins/images/admin-text.png' %}" alt="home"
                                class="dark-logo" />
                            <!--This is light logo text--><img src="{% static 'plugins/images/admin-text-dark.png' %}" alt="home"
                                class="light-logo" />
                        </span> </a>
                </div>
                <!-- /Logo -->
                <ul class="nav navbar-top-links navbar-right pull-right">
                    <li>
                        <a class="nav-toggler open-close waves-effect waves-light hidden-md hidden-lg"
                            href="javascript:void(0)"><i class="fa fa-bars"></i></a>
                    </li>
                    <li>
                        <a class="profile-pic" href="#"> <img src="../{{request.user.profile.profile_image.url}}" alt="user-img"
                                width="36" class="img-circle"><b class="hidden-xs">{{request.user.profile.full_name}}</b></a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-header -->
            <!-- /.navbar-top-links -->
            <!-- /.navbar-static-side -->
        </nav>
        <!-- End Top Navigation -->
        <!-- ============================================================== -->
        <!-- Left Sidebar - style you can find in sidebar.scss  -->
        <!-- ============================================================== -->
        <div class="navbar-default sidebar" role="navigation">
            <div class="sidebar-nav slimscrollsidebar">
                <div class="sidebar-head">
                    <h3><span class="fa-fw open-close"><i class="ti-close ti-menu"></i></span> <span
                            class="hide-menu">Navigation</span></h3>
                </div>
                <ul class="nav" id="side-menu">
                    <li style="padding: 70px 0 0;">
                        <a href="javascript:void(0)" class="waves-effect"><i class="fa fa-clock-o fa-fw"
                                aria-hidden="true"></i>Profile</a>
                    </li>
                    <li>
                        <a href="{% url 'profile_crud:dashboard'%}" class="waves-effect"><i class="fa fa-user fa-fw"
                                aria-hidden="true"></i>Dashboard</a>
                    </li>
                </ul>
            </div>
        </div>

        <div id="page-wrapper">
            <div class="container-fluid">
                <div class="row bg-title">
                    <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
                        <h4 class="page-title">Profile page</h4>
                    </div>
                    <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
                        <a href="https://wrappixel.com/templates/ampleadmin/" target="_blank"></a>
                            
                        <ol class="breadcrumb">
                            <li><a href="#">Dashboard</a></li>
                            <li class="active">Profile Page</li>
                        </ol>
                    </div>
                </div>
                <!-- /.row -->
                <!-- .row -->
                <div class="row">
                    <div class="col-md-4 col-xs-12">
                        <div class="white-box">

                            <div class="user-bg"> <img width="100%" alt="user" src="../{{request.user.profile.profile_image.url}}">
                                <div class="overlay-box">
                                    <div class="user-content">

                                        <a href="javascript:void(0)"><img src="../{{request.user.profile.profile_image.url}}"
                                                class="thumb-lg img-circle" alt="img"></a>

                                        <h4 class="text-white">{{request.user.profile.user}}</h4>

                                        <h5 class="text-white">{{request.user.profile.phone_number}}</h5>
                                    </div>
                                </div>
                            </div>
                            <div class="user-btm-box">

                            </div>
                        </div>
                    </div>
                    <div class="col-md-8 col-xs-12">
                        <div class="white-box">
                            <form method ="POST" enctype="multipart/form-data" class="form-horizontal form-material">
                                {% csrf_token %}
                                {{form.user}}
                                <div class="form-group">
                                    <label class="col-md-12">Full Name</label>
                                    <div class="col-md-12">
                                        {{form.full_name}} </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-12">Phone No</label>
                                    <div class="col-md-12">
                                        {{form.phone_number}} </div>
                                </div>

                                <div class="form-group">
                                    <label class="col-md-12">Upload Image</label>
                                    <div class="col-md-12">
                                        {{form.profile_image}} </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-sm-12">
                                        <button type="submit" class="btn btn-success">Update Profile</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
                <!-- /.row -->
            </div>
            <!-- /.container-fluid -->
            <footer class="footer text-center"> 2017 &copy; Ample Admin brought to you by wrappixel.com </footer>
        </div>
        <!-- /#page-wrapper -->
    </div>
    <!-- /#wrapper -->
    <!-- jQuery -->
    <script src="{% static 'plugins/bower_components/jquery/dist/jquery.min.js' %}"></script>
    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'bootstrap/dist/js/bootstrap.min.js' %}"></script>
    <!-- Menu Plugin JavaScript -->
    <script src="{% static 'plugins/bower_components/sidebar-nav/dist/sidebar-nav.min.js' %}"></script>
    <!--slimscroll JavaScript -->
    <script src="{% static 'js/jquery.slimscroll.js' %}"></script>
    <!--Wave Effects -->
    <script src="{% static 'js/waves.js' %}"></script>
    <!-- Custom Theme JavaScript -->
    <script src="{% static 'js/custom.min.js' %}"></script>
</body>

</html>

profile_crud/templates/html/update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>update</title>
</head>
<body>
<form method="Post">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">Submit</button>
</form>
</body>
</html>